[package]
name = "chess-0x539"
version = "0.1.0"
authors = ["l0x539 <nogues322@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
array_tool = "1.0.3"
wasm-bindgen = "0.2.70"
